export const PROMPTS: { id: string; content: string }[] = [
  { id: "1", content: "A lábadra lehet húzni..." },
  { id: "2", content: "A hűtőben megtalálható..." },
  { id: "3", content: "Olyasmi, amit nem vinnél magaddal egy első randira..." },
  { id: "4", content: "Egy kifogás, amiért elkéstél..." },
  { id: "5", content: "Valami, amitől hangosan felkiáltasz..." },
  { id: "6", content: "Egy mondat, amit egy rendőrnek nem érdemes mondani..." },
  { id: "7", content: "Olyasmi, amit titokban csinálsz, amikor senki sem lát..." },
  { id: "8", content: "Egy furcsa név egy kutyának..." },
  { id: "9", content: "Valami, ami mindig eltűnik a lakásban..." },
  { id: "10", content: "Egy mondat, amitől azonnal kínossá válik egy családi ebéd..." },

  { id: "11", content: "Olyasmi, amit egy nagymama mondhat..." },
  { id: "12", content: "Valami, amit egy esküvőn nem szeretnél hallani..." },
  { id: "13", content: "Egy teljesen értelmetlen szuperképesség..." },
  { id: "14", content: "Olyasmi, amitől felébredsz éjszaka..." },
  { id: "15", content: "Egy mondat, amivel borzalmasan lehet szakítani valakivel..." },
  { id: "16", content: "Valami, amit biztosan nem ennél meg..." },
  { id: "17", content: "Egy nagyon rossz név egy étteremnek..." },
  { id: "18", content: "Olyasmi, amit a főnököd előtt nem csinálnál..." },
  { id: "19", content: "Egy dolog, amitől egyből gyanússá válik valaki..." },
  { id: "20", content: "Mit mondanál, ha véletlenül betörnél valaki házába?" },

  { id: "21", content: "Valami, ami ragad..." },
  { id: "22", content: "Valami, ami büdös..." },
  { id: "23", content: "Egy mondat, amit egy állásinterjún jobb elkerülni..." },
  { id: "24", content: "Egy hely, ahol nagyon kellemetlen lenne elaludni..." },
  { id: "25", content: "Olyasmi, amit egy gyerek biztosan megkérdez..." },
  { id: "26", content: "Egy ok, amiért nem veszed fel a telefont..." },
  { id: "27", content: "Valami, amitől azonnal rossz napod lesz..." },
  { id: "28", content: "Egy mondat, amitől egy pincér ideges lesz..." },
  { id: "29", content: "Egy szokatlan dolog, amit magaddal vinnél egy lakatlan szigetre..." },
  { id: "30", content: "Mit mondanál, ha egy idegen ülne a kanapédon?" },

  { id: "31", content: "Valami, amit lehet dobálni..." },
  { id: "32", content: "Valami, amit jobb nem megszagolni..." },
  { id: "33", content: "Egy rossz ajándék karácsonyra..." },
  { id: "34", content: "Egy mondat, amit nem akarsz hallani az orvostól..." },
  { id: "35", content: "Egy dolog, amit az emberek rendszeresen elfelejtenek..." },
  { id: "36", content: "Egy hülye kifogás arra, hogy miért nem készült el a házi feladat..." },
  { id: "37", content: "Olyasmi, amit nem szeretnél találni az ágyadban..." },
  { id: "38", content: "Egy furcsa foglalkozás, amit szívesen kipróbálnál..." },
  { id: "39", content: "Mit kiabálnál, ha megnyernéd a lottót?" },
  { id: "40", content: "Egy mondat, amivel garantáltan elrontasz egy romantikus pillanatot..." },

  { id: "41", content: "Valami, ami piros..." },
  { id: "42", content: "Valami, ami nagyon nehéz..." },
  { id: "43", content: "Egy dolog, amit nem szeretnél a levesedben találni..." },
  { id: "44", content: "Egy rossz név egy rockzenekarnak..." },
  { id: "45", content: "Valami, amit az emberek a zuhany alatt csinálnak..." },
  { id: "46", content: "Egy mondat, amitől egy taxisofőr furcsán nézne rád..." },
  { id: "47", content: "Egy kifogás arra, hogy miért nincs rajtad nadrág..." },
  { id: "48", content: "Olyasmi, amit egy szellem mondhatna..." },
  { id: "49", content: "Mit mondanál, ha egy UFO leszállna előtted?" },
  { id: "50", content: "Egy dolog, amitől garantáltan felébredsz..." },

  { id: "51", content: "Valami, amit meg lehet nyomni..." },
  { id: "52", content: "Valami, amit nem szabad mikróba tenni..." },
  { id: "53", content: "Egy mondat, ami rosszul hangzik egy repülőgép pilótájától..." },
  { id: "54", content: "Egy furcsa dolog, amit valaki gyűjthet..." },
  { id: "55", content: "Egy indok, amiért valakit kirúghatnak..." },
  { id: "56", content: "Mit mondanál egy beszélő macskának?" },
  { id: "57", content: "Egy kínos dolog, ami megtörténhet egy randin..." },
  { id: "58", content: "Egy mondat, amitől az anyukád mérges lenne..." },
  { id: "59", content: "Olyasmi, amit egy kalóz mondhat..." },
  { id: "60", content: "Egy nagyon rossz jelszó..." },

  { id: "61", content: "Valami, ami kerek..." },
  { id: "62", content: "Valami, amit fel lehet fújni..." },
  { id: "63", content: "Egy nevetséges ok arra, hogy valaki híres legyen..." },
  { id: "64", content: "Mit mondanál, ha rajtakapnának, hogy a hűtőt fosztogatod éjjel?" },
  { id: "65", content: "Egy mondat, amitől egy pap meglepődne..." },
  { id: "66", content: "Egy tárgy, amit nagyon furcsa lenne zsebben hordani..." },
  { id: "67", content: "Egy borzalmas név egy szépségszalonnak..." },
  { id: "68", content: "Valami, amitől egy kutya izgatott lesz..." },
  { id: "69", content: "Egy mondat, amit egy temetésen nem illik mondani..." },
  { id: "70", content: "Egy dolog, amit soha nem adnál kölcsön..." },

  { id: "71", content: "Valami, amit meg lehet törni..." },
  { id: "72", content: "Valami, ami puha..." },
  { id: "73", content: "Egy értelmetlen találmány, amit mégis megvennél..." },
  { id: "74", content: "Egy kifogás, amit egy gyerek találna ki..." },
  { id: "75", content: "Mit mondanál, ha reggel egy kecske lenne a nappalidban?" },
  { id: "76", content: "Egy mondat, amit nem akarsz hallani a fodrásztól..." },
  { id: "77", content: "Egy szokatlan dolog, amit valaki reggelizhet..." },
  { id: "78", content: "Egy nagyon rossz filmcím..." },
  { id: "79", content: "Valami, amiről az emberek rendszeresen hazudnak..." },
  { id: "80", content: "Egy mondat, ami után valószínűleg menekülni kezdenél..." },

  { id: "81", content: "Valami, aminek kereke van..." },
  { id: "82", content: "Valami, ami hangos..." },
  { id: "83", content: "Egy mondat, amit egy bankrabló mondhat..." },
  { id: "84", content: "Egy hülye név egy szuperhősnek..." },
  { id: "85", content: "Mit mondanál, ha láthatatlanná válnál?" },
  { id: "86", content: "Egy ok, amiért valaki kizárhatja magát a lakásból..." },
  { id: "87", content: "Egy tárgy, amitől furcsán néznének rád a buszon..." },
  { id: "88", content: "Egy mondat, amit egy robot mondhatna az emberiségnek..." },
  { id: "89", content: "Egy dolog, amit soha nem tennél fel az internetre..." },
  { id: "90", content: "Egy nevetséges törvény, amit bevezetnél..." },

  { id: "91", content: "Valami, ami hideg..." },
  { id: "92", content: "Valami, amit meg lehet enni kézzel..." },
  { id: "93", content: "Egy mondat, amit egy tanár nem szeretne hallani..." },
  { id: "94", content: "Egy furcsa dolog, amit egy szállodai szobában találhatsz..." },
  { id: "95", content: "Egy indok, amiért nem mennél dolgozni..." },
  { id: "96", content: "Mit mondanál, ha találkoznál saját magaddal?" },
  { id: "97", content: "Egy rossz név egy gyerekjátéknak..." },
  { id: "98", content: "Valami, amitől egy macska megijed..." },
  { id: "99", content: "Egy mondat, amitől egy szerelő rögtön drágábbnak tűnik..." },
  { id: "100", content: "Egy dolog, amit semmiképp sem akarsz elveszíteni..." },

  { id: "101", content: "Valami, amit meg lehet mászni..." },
  { id: "102", content: "Valami, ami csúszós..." },
  { id: "103", content: "Egy értelmetlen kifogás arra, hogy miért nem fizettél..." },
  { id: "104", content: "Mit mondanál, ha egy pingvin kopogna az ajtódon?" },
  { id: "105", content: "Egy mondat, amit nem szeretnél hallani ejtőernyőzés közben..." },
  { id: "106", content: "Egy nagyon furcsa ételpárosítás..." },
  { id: "107", content: "Egy rossz név egy óvodának..." },
  { id: "108", content: "Valami, amit mindenki csinál, de senki sem vallja be..." },
  { id: "109", content: "Egy mondat, amit egy gonosztevő mondana..." },
  { id: "110", content: "Egy dolog, amit egy milliomos fölöslegesen megvehet..." },

  { id: "111", content: "Valami, ami lebeg..." },
  { id: "112", content: "Valami, amit be lehet kapcsolni..." },
  { id: "113", content: "Egy mondat, amitől megállna a beszélgetés egy randin..." },
  { id: "114", content: "Egy furcsa dolog, amit magaddal vihetsz nyaralni..." },
  { id: "115", content: "Mit mondanál, ha egy napra te lennél az ország vezetője?" },
  { id: "116", content: "Egy nevetséges ok egy válásra..." },
  { id: "117", content: "Egy rossz név egy hajónak..." },
  { id: "118", content: "Valami, amit egy szomszéd miatt hallhatsz éjszaka..." },
  { id: "119", content: "Egy mondat, amit egy pincében nem akarsz hallani..." },
  { id: "120", content: "Egy olyan munka, amit egy napig kipróbálnál..." },

  { id: "121", content: "Valami, ami világít..." },
  { id: "122", content: "Valami, amit lehet hajtogatni..." },
  { id: "123", content: "Egy mondat, amitől egy esküvői fotós ideges lenne..." },
  { id: "124", content: "Egy teljesen fölösleges alkalmazás ötlete..." },
  { id: "125", content: "Mit mondanál, ha egy dinoszaurusz jelenne meg az utcán?" },
  { id: "126", content: "Egy kifogás, ami olyan rossz, hogy már majdnem jó..." },
  { id: "127", content: "Egy furcsa név egy kocsmának..." },
  { id: "128", content: "Valami, amitől egyből kínos lesz egy liftút..." },
  { id: "129", content: "Egy mondat, amit egy repülőtéren nem érdemes kiabálni..." },
  { id: "130", content: "Egy dolog, amit gyerekként sokkal jobbnak gondoltál..." },

  { id: "131", content: "Valami, ami könnyen eltörik..." },
  { id: "132", content: "Valami, amit a falra lehet tenni..." },
  { id: "133", content: "Egy nevetséges becenév..." },
  { id: "134", content: "Mit mondanál, ha tudnád, hogy senki sem hallja?" },
  { id: "135", content: "Egy mondat, amitől egy szakács megsértődne..." },
  { id: "136", content: "Egy különös dolog, amit egy múzeumban kiállítanál..." },
  { id: "137", content: "Egy rossz név egy társkereső oldalnak..." },
  { id: "138", content: "Valami, amitől azonnal gyanakodni kezdesz egy hotelben..." },
  { id: "139", content: "Egy kifogás arra, hogy miért beszélsz magadban..." },
  { id: "140", content: "Egy mondat, amit egy időutazó mondhatna..." },

  { id: "141", content: "Valami, ami édes..." },
  { id: "142", content: "Valami, amit össze lehet csukni..." },
  { id: "143", content: "Egy dolog, amit nem szeretnél egy nyilvános vécében találni..." },
  { id: "144", content: "Egy mondat, amivel furcsán lehet bemutatkozni..." },
  { id: "145", content: "Mit mondanál, ha holnaptól nem kellene dolgoznod?" },
  { id: "146", content: "Egy teljesen felesleges világrekord..." },
  { id: "147", content: "Egy borzalmas név egy légitársaságnak..." },
  { id: "148", content: "Valami, amit egy ember túl sokáig tud nézegetni..." },
  { id: "149", content: "Egy mondat, amit nem akarsz hallani fogorvosi kezelés közben..." },
  { id: "150", content: "Egy furcsa dolog, amit magaddal vinnél munkába..." },

  { id: "151", content: "Valami, ami hosszú..." },
  { id: "152", content: "Valami, amit meg lehet tölteni..." },
  { id: "153", content: "Egy mondat, amitől egy biztonsági őr rád figyelne..." },
  { id: "154", content: "Egy nevetséges indok arra, hogy miért kell új telefon..." },
  { id: "155", content: "Mit mondanál, ha egy napra állattá változnál?" },
  { id: "156", content: "Egy rossz név egy gyógyszernek..." },
  { id: "157", content: "Egy tárgy, aminek nagyon furcsa lenne emberi neve..." },
  { id: "158", content: "Egy mondat, amit egy gyerek valószínűleg félreértene..." },
  { id: "159", content: "Egy dolog, amitől egy családi nyaralás katasztrófává válhat..." },
  { id: "160", content: "Egy különös szolgáltatás, amiért valaki még fizetne is..." },

  { id: "161", content: "Valami, aminek szaga van..." },
  { id: "162", content: "Valami, amit lehet rázni..." },
  { id: "163", content: "Egy rossz mondat egy első találkozás végére..." },
  { id: "164", content: "Mit mondanál, ha hirtelen minden állat értené, amit mondasz?" },
  { id: "165", content: "Egy teljesen abszurd házirend..." },
  { id: "166", content: "Egy furcsa név egy hotelnek..." },
  { id: "167", content: "Valami, amit jobb lenne nem tudni a szomszédodról..." },
  { id: "168", content: "Egy mondat, amitől az utasok leszállnának a buszról..." },
  { id: "169", content: "Egy kifogás arra, hogy miért etted meg valaki más ételét..." },
  { id: "170", content: "Egy dolog, amitől egy egyszerű bevásárlás káoszba fulladhat..." },

  { id: "171", content: "Valami, ami lyukas..." },
  { id: "172", content: "Valami, amit fel lehet akasztani..." },
  { id: "173", content: "Egy mondat, amit egy idegennek furcsa lenne súgni..." },
  { id: "174", content: "Egy nevetséges termék, amit tévéreklámban árulnál..." },
  { id: "175", content: "Mit mondanál, ha reggel arra ébrednél, hogy híres vagy?" },
  { id: "176", content: "Egy nagyon rossz név egy banknak..." },
  { id: "177", content: "Egy dolog, amit egy idegen bolygón elsőként megkeresnél..." },
  { id: "178", content: "Egy mondat, amitől egy nyaralás rögtön rosszul indul..." },
  { id: "179", content: "Egy kifogás arra, hogy miért van nálad egy lapát..." },
  { id: "180", content: "Egy furcsa dolog, amit valaki az interneten rendelhet..." },

  { id: "181", content: "Valami, ami gyors..." },
  { id: "182", content: "Valami, amit el lehet ásni..." },
  { id: "183", content: "Egy mondat, amit egy liftben teljesen váratlan lenne hallani..." },
  { id: "184", content: "Egy értelmetlen ünnep, amit bevezetnél..." },
  { id: "185", content: "Mit mondanál, ha öt perc múlva vége lenne a világnak?" },
  { id: "186", content: "Egy borzalmas név egy óriáskeréknek..." },
  { id: "187", content: "Egy tárgy, amitől egy rendőr furcsán nézne rád..." },
  { id: "188", content: "Egy mondat, ami nagyon rosszul hangzik egy sebésztől..." },
  { id: "189", content: "Egy kifogás arra, hogy miért nem tudsz ma hazamenni..." },
  { id: "190", content: "Egy dolog, amit egy milliárdos csak azért venne meg, mert megteheti..." },

  { id: "191", content: "Valami, ami szőrös..." },
  { id: "192", content: "Valami, amit össze lehet kötni..." },
  { id: "193", content: "Egy mondat, amitől mindenki rád nézne egy csendes teremben..." },
  { id: "194", content: "Egy nevetséges új tantárgy az iskolában..." },
  { id: "195", content: "Mit mondanál, ha egy kívánságod azonnal teljesülhetne?" },
  { id: "196", content: "Egy rossz név egy vidámparknak..." },
  { id: "197", content: "Egy dolog, amit semmiképpen nem szeretnél egy idegentől ajándékba kapni..." },
  { id: "198", content: "Egy mondat, amitől azonnal tudod, hogy valami nincs rendben..." },
  { id: "199", content: "Egy teljesen hülye ok, amiért valaki felhívná a segélyhívót..." },
  { id: "200", content: "Mit mondanál, ha most azonnal bárhová teleportálhatnál?" },
];

export const ACTIVE_GAME_STORAGE_KEY = "magma:active-game";
